name: Advanced yml sample
on:
    pull_request:
        types:
            - opened
            - closed
        branches:
            - main
            - feat/*
            - bugfix/*
            - hotfix/*
            - release/*
    workflow_dispatch:
    push:
        branches:
            - main
            - feat/*
            - bugfix/*
            - hotfix/*
            - release/*
        paths-ignore:
            - '**.yml'
            - '**.json'
    schedule:
        - cron: '0 0 * * *'

jobs:
    start_project
          

