name: Advanced yml sample
on:
    pull_request:
        types:
            - opened
            - closed
        branches:
            - main
            - feat/*
            - bugfix/*
            - hotfix/*
            - release/*
    workflow_dispatch:
    push:
        branches:
            - main
            - feat/*
            - bugfix/*
            - hotfix/*
            - release/*
        paths-ignore:
            - '**.yml'
            - '**.json'
    schedule:
        - cron: '0 0 * * *'

jobs:
    start_project:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: set up node js
              uses: actions/setup-node@v3
              with:
                node-version: '18'
            - name: install dependencies
              run: npm ci --force
            - name: Install playwright
              run: npx playwright install --with-dep
            #- name: wait for local host
            #  run: |
            #    npm run start
            #    echo 'Waiting for local host'
            #    done
            - name: Run tests
             #   - 4200:4200
              run: npx playwright test DemoQA
    build_project:
        needs: start_project
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: install dependencies
              run: npm ci --force
            - name: Install playwright
              run: npx playwright install --with-dep
            - name: Run tests
              run: npx playwright test lambdatests
             
          

